name: Deploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::010928211341:role/OIDC-Node-react
          aws-region: ap-south-1
          role-session-name: github-actions

      - name: Verify
        run: aws sts get-caller-identity

